name: Docker Automation
on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Docker Login, build
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/getting-started:latest .
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/getting-started

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: AWS ECR Push
        run: |
          aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 012889719104.dkr.ecr.us-east-1.amazonaws.com
          sudo docker tag getting-started:latest 012889719104.dkr.ecr.us-east-1.amazonaws.com/hcl/getting-started
          sudo docker push 012889719104.dkr.ecr.us-east-1.amazonaws.com/hcl/getting-started
    
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Compose up
        run: |
          sudo docker compose up -d
          sudo docker ps
